/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.view;

import br.com.fiap.controller.CtrlDeletarLancamento;
import br.com.fiap.dao.LancamentoDAO;
import br.com.fiap.entity.Lancamento;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago
 */
public class FormListarLancamento extends javax.swing.JFrame {

    String[][] matrizLancamento;
    int codigoLancamento;

    public void setCodigoLancamento(int codigoLancamento) {
        this.codigoLancamento = codigoLancamento;
    }
    

    public FormListarLancamento() {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNovoLancamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabLancamentos = new javax.swing.JTable();
        lblDashboard = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnDeletarLancamento = new javax.swing.JButton();
        btnALterarLancamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(723, 420));
        setSize(new java.awt.Dimension(723, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-05 51x51.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel4.setText("Lançamento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btnNovoLancamento.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Mais 20x20.png"))); // NOI18N
        btnNovoLancamento.setText("Novo");
        btnNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLancamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 80, 100, 40));

        tabLancamentos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "GRUPO", "HORA LANÇAMENTO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabLancamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 690, 230));

        lblDashboard.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel10.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel10.setText("Lançamentos");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 9, -1, -1));

        btnDeletarLancamento.setText("Deletar");
        btnDeletarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLancamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, 40));

        btnALterarLancamento.setText("Alterar");
        btnALterarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALterarLancamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnALterarLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //CHAMANDO FORMULARIO PRINCIPAL
        FormPrincipal fp = new FormPrincipal();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void btnNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLancamentoActionPerformed
        // CHAMANDO O FORMULARIO NOVO LANÇAMENTO
        FormSalvarLancamento fnl = new FormSalvarLancamento();
        this.dispose();
        fnl.setVisible(true);
    }//GEN-LAST:event_btnNovoLancamentoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizarTabela();
    }//GEN-LAST:event_formWindowOpened

    private void btnDeletarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLancamentoActionPerformed
        int linha = tabLancamentos.getSelectedRow();
        if (linha != -1) {
            if (this.codigoLancamento != -1) {
                int codLancamento = Integer.parseInt(String.valueOf(tabLancamentos.getValueAt(linha, 0)));
                CtrlDeletarLancamento ctrlLancamento = new CtrlDeletarLancamento();
                if (ctrlLancamento.confirmaExclusao()) {
                    ctrlLancamento.excluirLancamento(codLancamento);
                    atualizarTabela();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um lançamento da lista para deletar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um lançamento da lista para deletar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        }
    }//GEN-LAST:event_btnDeletarLancamentoActionPerformed

    private void btnALterarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALterarLancamentoActionPerformed

        int linha = tabLancamentos.getSelectedRow();
        if (linha != -1) {
            FormSalvarLancamento fnl = new FormSalvarLancamento();
            int obj = Integer.parseInt(String.valueOf(tabLancamentos.getValueAt(linha, 0)));
            fnl.setCodLancamento(obj);
            this.dispose();
            fnl.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um lançamento da lista para alterar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        }

    }//GEN-LAST:event_btnALterarLancamentoActionPerformed

    public void atualizarTabela() {

        LancamentoDAO dao = new LancamentoDAO();

        List<Lancamento> lista = dao.listar();
        matrizLancamento = new String[lista.size()][4];
        Lancamento lancamento;
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        String[] colunas = {"ID", "GRUPO", "HORA LANÇAMENTO", "STATUS"};
        String status = "";
        for (int i = 0; i < lista.size(); i++) {

            lancamento = lista.get(i);
            if (lancamento.getStatus() == 1) {
                status = "Pré-Lançamento";
            } else if (lancamento.getStatus() == 2) {
                status = "Lançamento Sucesso";
            } else if (lancamento.getStatus() == 3) {
                status = "Falhou";
            }

            matrizLancamento[i][0] = String.valueOf(lancamento.getCodLancamento());
            matrizLancamento[i][1] = String.valueOf(dao.buscarNomeGrupo(lancamento.getCodGrupo()));
            matrizLancamento[i][2] = lancamento.getHorLancamento();
            matrizLancamento[i][3] = String.valueOf(status);

        }

        TableModel modeloTabela = new DefaultTableModel(matrizLancamento, colunas);
        tabLancamentos.setModel(modeloTabela);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarLancamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarLancamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnALterarLancamento;
    private javax.swing.JButton btnDeletarLancamento;
    private javax.swing.JButton btnNovoLancamento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JTable tabLancamentos;
    // End of variables declaration//GEN-END:variables
}
