/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.view;

import br.com.fiap.controller.CtrlDeletarPeriodo;
import br.com.fiap.controller.CtrlSalvarPeriodo;
import br.com.fiap.entity.Periodo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rm73889
 */
public class FormSalvarPeriodo extends javax.swing.JFrame {

    private int codPeriodo = -1;

    public void setCodPeriodo(int codPeriodo) {
        this.codPeriodo = codPeriodo;
    }

    /**
     * Creates new form FormNovoPeriodo2
     */
    public FormSalvarPeriodo() {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
        lblPeriodo.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JTextField();
        btnCancelarPeriodo = new javax.swing.JButton();
        btnSalvarPeriodo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acme Rocket");
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(723, 420));
        setPreferredSize(new java.awt.Dimension(723, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(723, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setText("*Período:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 320, -1));

        btnCancelarPeriodo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnCancelarPeriodo.setText("Cancelar");
        btnCancelarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, -1));

        btnSalvarPeriodo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnSalvarPeriodo.setText("Salvar");
        btnSalvarPeriodo.setMaximumSize(new java.awt.Dimension(77, 23));
        btnSalvarPeriodo.setMinimumSize(new java.awt.Dimension(77, 23));
        btnSalvarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel2.setText("Novo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lblDashboard.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-01 51x51.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 8, -1, -1));

        lblPeriodo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblPeriodo.setText("Períodos");
        lblPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPeriodoMouseClicked(evt);
            }
        });
        getContentPane().add(lblPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 8, -1, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 28)); // NOI18N
        jLabel8.setText("Período");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel3.setText("* Campos obrigatórios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //CHAMANDO FORMULARIO PRINCIPAL
        FormPrincipal fp = new FormPrincipal();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPeriodoMouseClicked
        //CHAMANDO FORMULARIO PERIODOS(LISTA)
        this.voltarParaLista();
    }//GEN-LAST:event_lblPeriodoMouseClicked

    private void btnCancelarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPeriodoActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar ?", "Selecione uma opção", JOptionPane.YES_NO_OPTION) == 0) {
            this.voltarParaLista();
        }
    }//GEN-LAST:event_btnCancelarPeriodoActionPerformed

    private void btnSalvarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPeriodoActionPerformed
        String nomePeriodo = txtPeriodo.getText();
        CtrlSalvarPeriodo ctrlPeriodo = new CtrlSalvarPeriodo();
        if (this.codPeriodo == -1) {
           if(ctrlPeriodo.inserirPeriodo(nomePeriodo)){
                this.voltarParaLista();
           }
        } else {
            if(ctrlPeriodo.alterarPeriodo(codPeriodo, nomePeriodo)){
                this.voltarParaLista();
            }
        }
        ctrlPeriodo = null;

    }//GEN-LAST:event_btnSalvarPeriodoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (this.codPeriodo != -1) {
            CtrlSalvarPeriodo ctrlPeriodo = new CtrlSalvarPeriodo();
            Periodo p = ctrlPeriodo.carregarPeriodo(codPeriodo);
            txtPeriodo.setText(p.getNomPeriodo());
            ctrlPeriodo = null;

        }
    }//GEN-LAST:event_formWindowOpened

    private void voltarParaLista() {
        this.dispose();
        FormListarPeriodo lf = new FormListarPeriodo(); //lf -> Last Form
        lf.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSalvarPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSalvarPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSalvarPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSalvarPeriodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSalvarPeriodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPeriodo;
    private javax.swing.JButton btnSalvarPeriodo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JTextField txtPeriodo;
    // End of variables declaration//GEN-END:variables
}
