/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.view;

import br.com.fiap.controller.CtrlDeletarEvento;
import br.com.fiap.controller.CtrlListarEvento;
import br.com.fiap.entity.Evento;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago
 */
public class FormListarEvento extends javax.swing.JFrame {

    private String matrizLista[][];
    private int codEvento;

    public FormListarEvento() {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEventos = new javax.swing.JTable();
        btnNovoEvento = new javax.swing.JButton();
        lblDashboard = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDeletarEvento = new javax.swing.JButton();
        btnALterarEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(723, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(723, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Candara", 0, 28)); // NOI18N
        jLabel3.setText("Eventos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-06 51x51.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        tabEventos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "EVENTOS", "LOCAL", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabEventos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 670, 230));

        btnNovoEvento.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnNovoEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Mais 20x20.png"))); // NOI18N
        btnNovoEvento.setText("Novo");
        btnNovoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEventoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 80, 100, 40));

        lblDashboard.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel9.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel9.setText("Eventos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 9, -1, -1));

        btnDeletarEvento.setText("Deletar");
        btnDeletarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarEventoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, 40));

        btnALterarEvento.setText("Alterar");
        btnALterarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALterarEventoActionPerformed(evt);
            }
        });
        getContentPane().add(btnALterarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //CHAMANDO FORMULARIO PRINCIPAL
        FormPrincipal fp = new FormPrincipal();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void btnNovoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEventoActionPerformed
        //CHAMANDO FORMULARIO PARA NOVO EVENTO
        FormSalvarEvento fne = new FormSalvarEvento();
        this.dispose();
        fne.setVisible(true);
    }//GEN-LAST:event_btnNovoEventoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizarTabela();
    }//GEN-LAST:event_formWindowOpened

    private void tabEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEventosMouseClicked
        // TODO add your handling code here:
//        int linha = tabEventos.getSelectedRow();
//        if (linha != -1) {
//            FormSalvarEvento fne = new FormSalvarEvento();
//            int obj = Integer.parseInt(String.valueOf(tabEventos.getValueAt(linha, 0)));
//            fne.setCodEvento(obj);
//            this.dispose();
//            fne.setVisible(true);
//        }
    }//GEN-LAST:event_tabEventosMouseClicked

    private void btnDeletarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarEventoActionPerformed
        int linha = tabEventos.getSelectedRow();
        if (linha != -1) {
            if (this.codEvento != -1) {
                int codigoEvento = Integer.parseInt(String.valueOf(tabEventos.getValueAt(linha, 0)));
                CtrlDeletarEvento ctrlEvento = new CtrlDeletarEvento();
                if (ctrlEvento.confirmaExclusao()) {
                    ctrlEvento.excluirEvento(codigoEvento);
                    //this.voltarParaLista();
                    atualizarTabela();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um evento da lista para deletar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um evento da lista para deletar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        }

    }//GEN-LAST:event_btnDeletarEventoActionPerformed

    private void btnALterarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALterarEventoActionPerformed
        int linha = tabEventos.getSelectedRow();
        if (linha != -1) {
            FormSalvarEvento fng = new FormSalvarEvento();
            int obj = Integer.parseInt(String.valueOf(tabEventos.getValueAt(linha, 0)));
            fng.setCodEvento(obj);
            this.dispose();
            fng.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Selecione um evento da lista para alterar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_btnALterarEventoActionPerformed

    //ATUALIZANDO A TABELA
    public void atualizarTabela() {
        CtrlListarEvento ctrl = new CtrlListarEvento();
        List<Evento> lista = ctrl.carregarRegistros();

        matrizLista = new String[lista.size()][4];
        Evento evento;
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        String[] colunas = {"ID", "EVENTOS", "LOCAL", "DATA"};
        for (int i = 0; i < lista.size(); i++) {

            evento = lista.get(i);
            matrizLista[i][0] = String.valueOf(evento.getCodEvento());
            matrizLista[i][1] = evento.getNomEvento();
            matrizLista[i][2] = evento.getLocEvento();
            matrizLista[i][3] = formatoData.format(evento.getDatEvento());
            // matrizLista[i][3] = jLabel5.setIcon(icon);
//            matrizLista[i][4] = evento.getCaminhoFoto();

        }

        TableModel modeloTabela = new DefaultTableModel(matrizLista, colunas);
        tabEventos.setModel(modeloTabela);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnALterarEvento;
    private javax.swing.JButton btnDeletarEvento;
    private javax.swing.JButton btnNovoEvento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JTable tabEventos;
    // End of variables declaration//GEN-END:variables
}
