/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.view;

import br.com.fiap.controller.CtrlDeletarTurma;
import br.com.fiap.controller.CtrlListarTurma;
import br.com.fiap.entity.Turma;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thiago
 */
public class FormListarTurmas extends javax.swing.JFrame {

    String[][] matrizTurma;

    public FormListarTurmas() {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNovaTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTurmas = new javax.swing.JTable();
        lblDashboard = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDeletarTurma = new javax.swing.JButton();
        btnALterarTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(723, 420));
        setSize(new java.awt.Dimension(723, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-02 51x51.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 28)); // NOI18N
        jLabel4.setText("Turmas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        btnNovaTurma.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnNovaTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Mais 20x20.png"))); // NOI18N
        btnNovaTurma.setText("Novo");
        btnNovaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovaTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 80, 100, 40));

        tabTurmas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TURMA", "ANO", "PERÍODO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabTurmas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 690, 230));

        lblDashboard.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel8.setText("Turmas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 8, -1, -1));

        btnDeletarTurma.setText("Deletar");
        btnDeletarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, 40));

        btnALterarTurma.setText("Alterar");
        btnALterarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALterarTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnALterarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //CHAMANDO FORMULARIO PRINCIPAL
        FormPrincipal fp = new FormPrincipal();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void btnNovaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaTurmaActionPerformed
        //CHAMANDO FORMULARIO NOVA TURMA
        FormSalvarTurma fnt = new FormSalvarTurma();
        this.dispose();
        fnt.setVisible(true);
    }//GEN-LAST:event_btnNovaTurmaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizarTabela();
    }//GEN-LAST:event_formWindowOpened

    private void btnALterarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALterarTurmaActionPerformed
        int linha = tabTurmas.getSelectedRow();
        if (linha != -1) {
            FormSalvarTurma fst = new FormSalvarTurma();
            int obj = Integer.parseInt(String.valueOf(tabTurmas.getValueAt(linha,0)));
            fst.setCodTurma(obj);
            this.dispose();
            fst.setVisible(true);
        }else{
             JOptionPane.showMessageDialog(this, "Selecione uma turma da lista para alterar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        }
    }//GEN-LAST:event_btnALterarTurmaActionPerformed

    private void btnDeletarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTurmaActionPerformed
        int linha = tabTurmas.getSelectedRow();
        if (linha != -1) {
            int codTurma = Integer.parseInt(String.valueOf(tabTurmas.getValueAt(linha, 0)));
            CtrlDeletarTurma ctrlturma = new CtrlDeletarTurma();
            if (ctrlturma.confirmaExclusao()) {
                ctrlturma.excluirTurma(codTurma);
                atualizarTabela();
            }
        }else{
             JOptionPane.showMessageDialog(this, "Selecione uma turma da lista para deletar", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
        }
    }//GEN-LAST:event_btnDeletarTurmaActionPerformed

    /**
     * Atualiza a jTable
     */
    public void atualizarTabela() {
        CtrlListarTurma ctrlTurma = new CtrlListarTurma();
        List<Turma> lista = ctrlTurma.CarregarRegistrosTurmas();
        
        matrizTurma = new String[lista.size()][4];
        Turma turma;

        String[] colunas = {"ID", "TURMA", "ANO", "PERÍODO"};
        for (int i = 0; i < lista.size(); i++) {

            turma = lista.get(i);

            matrizTurma[i][0] = String.valueOf(turma.getCodTurma());
            matrizTurma[i][1] = turma.getNomTurma();
            matrizTurma[i][2] = String.valueOf(turma.getAnoTurma());
            matrizTurma[i][3] = ctrlTurma.obterNomePeriodo(turma);
        }

        TableModel modeloTabela = new DefaultTableModel(matrizTurma, colunas);
        tabTurmas.setModel(modeloTabela);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnALterarTurma;
    private javax.swing.JButton btnDeletarTurma;
    private javax.swing.JButton btnNovaTurma;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JTable tabTurmas;
    // End of variables declaration//GEN-END:variables
}
