/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiap.view;

import br.com.fiap.controller.CtrlListarEvento;
import br.com.fiap.controller.CtrlSalvarEvento;
import br.com.fiap.entity.Evento;
import java.awt.Color;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author Thiago
 */
public class FormSalvarEvento extends javax.swing.JFrame {

    /**
     * Creates new form FormSalvarEvento
     */
    public java.util.Date datEvento;
    private MaskFormatter mascaraData;
    private int codEvento = -1;

    public void setCodEvento(int codEvento) {
        this.codEvento = codEvento;
    }

    public FormSalvarEvento() {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
        lblEventos.setForeground(Color.blue);
    }

    public FormSalvarEvento(int elemento) {
        initComponents();
        setLocationRelativeTo(this);
        lblDashboard.setForeground(Color.blue);
        lblEventos.setForeground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLocalEvento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataEvento = new javax.swing.JTextField();
        try{
            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            txtDataEvento =  new JFormattedTextField(mascaraData);
        }catch(ParseException e){
            showMessageDialog(this, "Erro na mascara de data! \n "
                + "Error" + e);
        }
        btnCancelarEvento = new javax.swing.JButton();
        btnSalvarEvento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblEventos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(723, 420));
        setSize(new java.awt.Dimension(723, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel4.setText("Evento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-06 51x51.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setText("*Evento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        txtEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 320, -1));

        jLabel7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel7.setText("*Local");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        txtLocalEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtLocalEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 320, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel8.setText("*Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        txtDataEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtDataEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, -1));

        btnCancelarEvento.setText("Cancelar");
        btnCancelarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEventoMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 100, -1));

        btnSalvarEvento.setText("Salvar");
        btnSalvarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEventoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel2.setText("Novo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, -1, -1));

        lblDashboard.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 9, -1, -1));

        lblEventos.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        lblEventos.setText("Eventos");
        lblEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEventosMouseClicked(evt);
            }
        });
        getContentPane().add(lblEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fiap/images/Icones-Seta 16x16.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 9, -1, -1));

        jLabel5.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel5.setText("* Campos obrigatórios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel10.setText("* Campos obrigatórios");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //CHAMANDO FORMULARIO PRINCIPAL
        FormPrincipal fp = new FormPrincipal();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventosMouseClicked
        //CHAMANDO FORMULARIO EVENTOS(LISTA)
        this.dispose();
        FormListarEvento fe = new FormListarEvento();
        fe.setVisible(true);
    }//GEN-LAST:event_lblEventosMouseClicked

    private void btnSalvarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEventoActionPerformed
        String nomeEvento = txtEvento.getText();
        String locEvento = txtLocalEvento.getText();
        String datEventoFormated = txtDataEvento.getText();
        CtrlListarEvento ctrlLis = new CtrlListarEvento();
        CtrlSalvarEvento controle = new CtrlSalvarEvento();

        if (this.codEvento == -1) {

            if (controle.verificarExistencia(nomeEvento)) {
                JOptionPane.showMessageDialog(this, "Já existe um evento com esse nome");
            } else if (controle.inserirEvento(nomeEvento, locEvento, datEventoFormated)) {
                //  if (JOptionPane.showConfirmDialog(this, "Evento criado com sucesso, deseja criar outro evento?", "Selecione uma opcao", YES_NO_OPTION) == 0) {
                this.voltarParaLista();
            } 
        } else if (controle.verificarExistencia(nomeEvento)) {
            JOptionPane.showMessageDialog(this, "Já existe um evento com esse nome");
        } else {
            controle.editarEvento(codEvento, nomeEvento, locEvento, datEventoFormated);
            this.voltarParaLista();
        }
    }//GEN-LAST:event_btnSalvarEventoActionPerformed

    private void btnCancelarEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEventoMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar ?", "Selecione uma opção", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
            FormListarEvento lf = new FormListarEvento();
            lf.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarEventoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (codEvento != -1) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            CtrlSalvarEvento ctrlEvento = new CtrlSalvarEvento();
            Evento e = ctrlEvento.carregarEvento(codEvento);
            txtEvento.setText(e.getNomEvento());
            //txtDeletarEvento.setText(e.getDatEvento());
            txtLocalEvento.setText(e.getLocEvento());
            txtDataEvento.setText(formato.format(e.getDatEvento()));
            ctrlEvento = null;
        }
    }//GEN-LAST:event_formWindowOpened

    private void voltarParaLista() {
        this.dispose();
        FormListarEvento lf = new FormListarEvento(); //lf -> Last Form
        lf.setVisible(true);
    }

    private void limparCampos() {
        txtEvento.setText("");
        txtLocalEvento.setText("");
        txtDataEvento.setText("");
    }

    private boolean validaNomeAno(String nomeEvento, String datEventoFormated) {
        CtrlListarEvento ctrlLis = new CtrlListarEvento();
        ArrayList<Evento> lista = new ArrayList();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        lista = ctrlLis.carregarRegistros();
        CtrlSalvarEvento controle = new CtrlSalvarEvento();
        boolean aux = true;
        try {
            for (Evento e : lista) {
                String data = formatter.format(e.getDatEvento());
                if (e.getNomEvento().equalsIgnoreCase(nomeEvento) && data.equalsIgnoreCase(datEventoFormated)) {
                    JOptionPane.showMessageDialog(this, "Já existe um evento cadastrado com este nome neste ano!");
                    aux = false;
                    this.limparCampos();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro em Validar Evento" + e);
        }
        return aux;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSalvarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSalvarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSalvarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSalvarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSalvarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEvento;
    private javax.swing.JButton btnSalvarEvento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEventos;
    private javax.swing.JTextField txtDataEvento;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtLocalEvento;
    // End of variables declaration//GEN-END:variables
}
